import '../../styles/globals.css';

import { dir } from 'i18next';
import { Inter } from 'next/font/google';
import { ReactNode } from 'react';

import { languages } from '@/app/i18n/settings';

const inter = Inter({ subsets: ['latin'] });

export async function generateStaticParams() {
  return languages.map((lng) => ({ lng }));
}

export const metadata = {
  description: 'Generated by create next app',
  title: 'Create Next App',
};

export default function RootLayout({
  children,
  params: { lng },
}: {
  children: ReactNode;
  params: { lng: string };
}) {
  return (
    <html dir={dir(lng)} lang={lng}>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
